apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: nginx-login-pages
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nginx
    app.kubernetes.io/version: 1.25.3
    helm.sh/chart: nginx-15.5.1
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ include "common.names.namespace" . | quote }}
secrets:
- name: tyk-dev-dockercfg-d6bjw